### ISSUE TITLE
Resource: python environments guide by Talley Lambert

### ISSUE THREAD

**Issue by psobolewskiPhD** [JoachimGoedhart/Supervising-a-coding-project#1]
I came across this today, an overview of python environments. 
Maybe it's too late for you already, but I thought I would share.
https://hackmd.io/@talley/SJB_lObBi

I found it really helpful and wish I had it when I was starting!

**Comment by JoachimGoedhart** [comment]
Thanks Peter, it's never too late, I'll add it to the resources!
